### PR TITLE
Allow Naive passing of Julia `class_weight` dictionary

### PR DESCRIPTION
**Pull request by tylerjthomas9**
Ref: https://github.com/JuliaAI/MLJScikitLearnInterface.jl/issues/63

I have also added Aqua.jl to the tests, and fixed some compt errors that it identified. 

I introduced a function, `_prepare_param`, that handles preparing parameters being passed to the python constructor. Right now, it does nothing unless a Dictionary is passed. I tried to make it generic for future extensions to other types as needed.

### CODE REVIEW

**Review by ablaom — APPROVED** [review]
Looks good to me. Thanks for this valuable contribution, @tylerjthomas9 🙏🏾 

Could you have a look at the 1.6 fails, please?

**Comment by tylerjthomas9** [comment]
The 1.6 failures were due to Aqua.jl saying there is a method ambiguity in MLJModelInterface.jl. I have disabled checking them, for now. Something funky is going on with the nightly build. Do you think its worth investigating before merging?


Here is the 1.6 ambiguity from Aqua.jl:
```julia
1 ambiguities found
Ambiguity #1
in(x::MLJModelInterface.MLJType, itr::AbstractVector{T} where T) in MLJModelInterface at /Users/runner/.julia/packages/MLJModelInterface/ieFuy/src/equality.jl:158
in(x::T, r::AbstractRange{T}) where T in Base at range.jl:1088

Possible fix, define
  in(::T, ::AbstractRange{T}) where T<:MLJModelInterface.MLJType
```

**Comment by ablaom** [comment]
I've flagged MLJModelInterface.jl issue found by Aqua. I'm happy not to dig into the nightly issue at this time. So go ahead and merge/tag when ready.

**Comment by tylerjthomas9** [comment]
I am going to hold off on tagging because I want to look into the issues with fitting classifiers with a single class here and with CatBoost.jl, then just push a release with both of them.

**Pull request merged**
