### PR TITLE
fixed error in fitting unsupervised skmodels

### PR DESCRIPTION
**Pull request by OkonSamuel**
fix issue #10

### CODE REVIEW

**Comment by OkonSamuel** [comment]
For some reason tests are failing on julia v1.6DEV

**Comment by tlienart** [comment]
Not sure, passes fine locally on 1.6; we should allow failure on nightly but I don't know how to do that with the new travis files and their matrix crap

**Comment by OkonSamuel** [comment]
> Not sure, passes fine locally on 1.6; we should allow failure on nightly but I don't know how to do that with the new travis files and their matrix crap

Am still wondering while it failed on CI and passed locally for you

**Comment by tlienart** [comment]
:shrug: to be honest I think caring about tests passing on official release is good enough; if it becomes a thing that it fails on 1.5 beta or something then we should revisit but for now I would just ignore it

**Comment by OkonSamuel** [comment]
OK

**Pull request merged**
